import scrapy


class TedEuropaEuItem(scrapy.Item):
    document_id = scrapy.Field()
    description = scrapy.Field()
    country = scrapy.Field()
    publication_date = scrapy.Field()
    deadline = scrapy.Field()
    url = scrapy.Field()
    name = scrapy.Field()
    value = scrapy.Field()
    currency = scrapy.Field()
    total = scrapy.Field()
    short_description = scrapy.Field()
    contracting_country = scrapy.Field()
    award_date = scrapy.Field()
    contracting_authority = scrapy.Field()
    product_type = scrapy.Field()
    contracting_authority_city = scrapy.Field()
    cpv_code = scrapy.Field()
    lot_no = scrapy.Field()
    TI = scrapy.Field()
    ND = scrapy.Field()
    PD = scrapy.Field()
    OJ = scrapy.Field()
    TW = scrapy.Field()
    AU = scrapy.Field()
    OL = scrapy.Field()
    HD = scrapy.Field()
    CY = scrapy.Field()
    AA = scrapy.Field()
    HA = scrapy.Field()
    DS = scrapy.Field()
    NC = scrapy.Field()
    PR = scrapy.Field()
    TD = scrapy.Field()
    RP = scrapy.Field()
    TY = scrapy.Field()
    AC = scrapy.Field()
    PC = scrapy.Field()
    RC = scrapy.Field()
    IA = scrapy.Field()
    DI = scrapy.Field()
